-- Create table ITEM_DETAILS 
CREATE OR REPLACE TABLE SIMP_BOM.MASTER_DATA.T_MASTER_DATA_ITEM_DETAILS_ROOT  (
    ITEM_ID VARCHAR(21),
    ITEM_CLASS_NM VARCHAR(21),
    ITEM_DSC VARCHAR(21),
    DELETE_IND VARCHAR(21)
);