-- Create Table Sales Order Detail -- 

CREATE OR REPLACE TABLE T_SALES_ORDER_DETAIL (
    ORDER_ID VARCHAR(10) PRIMARY KEY,
    ORDER_DATE DATE,
    CUSTOMER_ID	VARCHAR(10),
    ITEM_ID	VARCHAR(10),
    QTY	INTEGER,
    PRICE FLOAT,
    CREATE_DATE DATE,
    CREATE_USER	VARCHAR(10)
);