-- Create table ORIG_BOM
CREATE OR REPLACE TABLE SIMP_BOM.MASTER_DATA.T_MASTER_DATA_ORIG_BOM  (
    INPUT_ITEM_ID VARCHAR(21),	
    ITEM_CLASS_NM VARCHAR(21),
    OUTPUT_ITEM_ID VARCHAR(21),
    LOC VARCHAR(21)
)