-- Insert Table CUSTOMER --

INSERT INTO T_CUSTOMER 
    (CUSTOMER_ID, ADDRESS, PHONE_NO, CATEGORY, STATUS, CREATE_DATE, CREATE_USER) 
VALUES
    ('CUST08', 'CHENNAI', '9551234567', 'regular', 'Active', '2023-01-15', 'ADMIN'),
    ('CUST09', 'THIRUNELVELI', '9552345678', 'regular', 'Active', '2023-02-20', 'ADMIN');,
    ('CUST03', 'MADURAI', '9553456789', 'silver', 'Inactive', '2023-03-05', 'ADMIN'),
    ('CUST04', 'SELAM', '9554567890', 'bronze', 'Active', '2023-04-10', 'ADMIN'),
    ('CUST05', 'PARAMAKUDI', '9555678901', 'gold', 'Active', '2023-05-25', 'ADMIN');
    