CREATE OR REPLACE TABLE SIMP_BOM.BMATHUB_ANALYSIS.T_SIM_BOM  (
    ITEM VARCHAR(21),
    ITEM_CLASS_NM VARCHAR(21),
    ANCHOR_ITEM_ID VARCHAR(21),
    BOM_NUM INTEGER,
    LOC	VARCHAR(21),
    DESCRIP VARCHAR(21)
)