CREATE OR REPLACE VIEW SIMP_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE AS
SELECT ITEM,
    ITEM_CLASS_NM,
    ANCHOR_ITEM_ID,
    BOM_NUM,
    LOC,
    CREATE_DTM,
    CREATE_USER
FROM SIMP_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE;

SELECT * FROM SIMP_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE;
DESC SIMP_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE: